Added automation for the testing

diff --git a/.github/workflows/python-validate.yml b/.github/workflows/python-validate.yml
--- a/.github/workflows/python-validate.yml
+++ b/.github/workflows/python-validate.yml
@@ -25,6 +25,8 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip poetry
+        poetry config virtualenvs.in-project true
+        poetry --version
         poetry install
     - name: Build package
       run: |
@@ -35,6 +37,31 @@ jobs:
     - name:  Type Lint with mypy
       run: |
         poetry run mypy .
-    - name: Test with pytest
+    - name: Build dynamically linked binary
+      run: |
+        poetry run pyoxidizer build
+        mkdir -p bin/
+        cp build/x86_64-unknown-linux-gnu/release/install/netplanner "bin/${LINUX_AMD64_BINARY}"
+        chmod 0644 "bin/${LINUX_AMD64_BINARY}"
+    - name: Try library installation
+      run: |
+        pip install dist/*.whl
+    - name: E2E Tests
+      run: |
+        chmod 0755 "bin/${LINUX_AMD64_BINARY}"
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/worker-config-old.yaml --output /run/systemd/networkd/worker-old configure
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/worker-config-new.yaml --output /run/systemd/networkd/worker-new configure
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/master-config-old.yaml --output /run/systemd/networkd/master-old configure
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/master-config-new.yaml --output /run/systemd/networkd/master-new configure
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/veth-trial.yaml --output /run/systemd/networkd/veth-trial configure
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/5g-worker --output /run/systemd/networkd/folder/5g-worker configure
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/5g-worker.yaml --output /run/systemd/networkd/5g-worker configure
+        # enable the netplan apply command
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/vm-config --output /run/systemd/networkd/folder/vm-config apply
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/vm-config.yaml --output /run/systemd/networkd/vm-config apply
+        # this should fail
+        bin/${LINUX_AMD64_BINARY} --debug --local --only-networkd --config examples/empty --output /run/systemd/networkd/empty configure || true
+
+    - name: Pytest
       run: |
         echo "This should later run the unit tests."
